// Package database provides PostgreSQL alert repository implementation.
package database

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/edr-platform/sigma-engine/internal/infrastructure/logger"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// maxDedupEventIDs bounds the event_ids array of a deduplicated alert so a
// noisy rule cannot grow one row without limit (the most recent are kept).
const maxDedupEventIDs = 1000

// PostgresAlertRepository implements AlertRepository using PostgreSQL.
type PostgresAlertRepository struct {
	pool *pgxpool.Pool
}

// NewPostgresAlertRepository creates a new PostgreSQL alert repository.
func NewPostgresAlertRepository(pool *pgxpool.Pool) *PostgresAlertRepository {
	return &PostgresAlertRepository{pool: pool}
}

// Create inserts a new alert into the database.
func (r *PostgresAlertRepository) Create(ctx context.Context, alert *Alert) (*Alert, error) {
	normalizeRelatedRuleIDs(alert)
	matchedFieldsJSON, _ := json.Marshal(alert.MatchedFields)
	contextDataJSON, _ := json.Marshal(alert.ContextData)
	contextSnapshotJSON, _ := json.Marshal(alert.ContextSnapshot)
	scoreBreakdownJSON, _ := json.Marshal(alert.ScoreBreakdown)
	if contextSnapshotJSON == nil {
		contextSnapshotJSON = []byte(`{}`)
	}
	if scoreBreakdownJSON == nil {
		scoreBreakdownJSON = []byte(`{}`)
	}
	// json.Marshal(nil map) yields "null"; store an empty object instead so
	// a merge never replaces existing context with JSON null.
	if string(contextSnapshotJSON) == "null" {
		contextSnapshotJSON = []byte(`{}`)
	}
	if string(scoreBreakdownJSON) == "null" {
		scoreBreakdownJSON = []byte(`{}`)
	}

	query := `
		INSERT INTO sigma_alerts (
			timestamp, agent_id, rule_id, rule_title, severity, category,
			event_count, event_ids, mitre_tactics, mitre_techniques,
			matched_fields, matched_selections, context_data,
			status, confidence, false_positive_risk,
			match_count, related_rules, combined_confidence,
			severity_promoted, original_severity,
			risk_score, context_snapshot, score_breakdown, related_rule_ids
		) VALUES (
			$1, $2, $3, $4, $5, $6,
			$7, $8, $9, $10,
			$11, $12, $13,
			$14, $15, $16,
			$17, $18, $19,
			$20, $21,
			$22, $23, $24, $25
		) RETURNING id, created_at, updated_at`

	err := r.pool.QueryRow(ctx, query,
		alert.Timestamp, alert.AgentID, alert.RuleID, alert.RuleTitle, alert.Severity, alert.Category,
		alert.EventCount, alert.EventIDs, alert.MitreTactics, alert.MitreTechniques,
		matchedFieldsJSON, alert.MatchedSelections, contextDataJSON,
		alert.Status, alert.Confidence, alert.FalsePositiveRisk,
		alert.MatchCount, alert.RelatedRules, alert.CombinedConfidence,
		alert.SeverityPromoted, alert.OriginalSeverity,
		alert.RiskScore, contextSnapshotJSON, scoreBreakdownJSON, alert.RelatedRuleIDs,
	).Scan(&alert.ID, &alert.CreatedAt, &alert.UpdatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to create alert: %w", err)
	}

	return alert, nil
}

// UpsertWithDedup atomically inserts a new alert or increments the event_count
// of an existing open/investigating alert within the deduplication window.
//
// This replaces the old FindRecent + conditional Create/IncrementEventCount
// pattern which had a read-modify-write race under concurrent writers.
//
// Returns (alert, true, nil)  → new alert inserted.
// Returns (alert, false, nil) → existing alert incremented (deduplicated).
func (r *PostgresAlertRepository) UpsertWithDedup(ctx context.Context, alert *Alert, dedupWindow time.Duration) (*Alert, bool, error) {
	normalizeRelatedRuleIDs(alert)
	matchedFieldsJSON, _ := json.Marshal(alert.MatchedFields)
	contextDataJSON, _ := json.Marshal(alert.ContextData)
	contextSnapshotJSON, _ := json.Marshal(alert.ContextSnapshot)
	scoreBreakdownJSON, _ := json.Marshal(alert.ScoreBreakdown)
	if contextSnapshotJSON == nil {
		contextSnapshotJSON = []byte(`{}`)
	}
	if scoreBreakdownJSON == nil {
		scoreBreakdownJSON = []byte(`{}`)
	}

	// Sliding window: an open alert keeps absorbing the same detection while
	// it recurs within dedupWindow of its LAST occurrence, but never longer
	// than maxAlertMergeAge after it was opened (so a pattern still active
	// tomorrow surfaces as a fresh alert instead of hiding in an old one).
	now := time.Now()
	dedupSince := now.Add(-dedupWindow)
	openedSince := now.Add(-maxAlertMergeAge)
	seenAt := alert.Timestamp
	if seenAt.IsZero() || seenAt.After(now) {
		seenAt = now
	}

	// The alert's own ID (generated by the alert generator) becomes the row's
	// primary key so every sink shares one canonical identity. A value that
	// is not a UUID (legacy "alert-…" IDs, tests) gets a fresh UUID.
	if _, perr := uuid.Parse(alert.ID); perr != nil {
		alert.ID = uuid.NewString()
	}

	// Strategy (one transaction):
	//   0. Take a transaction-scoped advisory lock on (agent_id, rule_id) so
	//      concurrent writers — other goroutines or engine replicas — for the
	//      same key serialise. (The former FOR UPDATE SKIP LOCKED let a second
	//      writer skip the locked row and insert a duplicate.)
	//   1. Find a recent open alert for the key within the dedup window.
	//   2. If found, merge the new evidence into it (count, event IDs, highest
	//      risk/severity/confidence with the matching context, related rules).
	//   3. Otherwise insert the new alert under its own ID.
	var resultAlert *Alert
	var isNew bool

	err := pgx.BeginTxFunc(ctx, r.pool, pgx.TxOptions{IsoLevel: pgx.ReadCommitted}, func(tx pgx.Tx) error {
		if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(hashtextextended($1, 0))`,
			alert.AgentID+"|"+alert.RuleID); err != nil {
			return fmt.Errorf("dedup lock: %w", err)
		}

		findQuery := `
			SELECT id FROM sigma_alerts
			WHERE agent_id = $1 AND rule_id = $2
			  AND COALESCE(last_seen_at, timestamp) >= $3
			  AND timestamp >= $4
			  AND status NOT IN ('resolved', 'false_positive')
			ORDER BY COALESCE(last_seen_at, timestamp) DESC
			LIMIT 1`

		var existingID string
		err := tx.QueryRow(ctx, findQuery, alert.AgentID, alert.RuleID, dedupSince, openedSince).Scan(&existingID)
		if err != nil && err != pgx.ErrNoRows {
			return fmt.Errorf("dedup lookup: %w", err)
		}

		if existingID != "" {
			// Step 2: merge evidence. Right-hand sides read the OLD row values,
			// so the CASE expressions compare against the pre-update state.
			// event_ids keeps the most recent maxDedupEventIDs entries.
			updateQuery := `
				UPDATE sigma_alerts
				SET event_count = event_count + 1,
				    event_ids   = (event_ids || $2)[GREATEST(1, cardinality(event_ids || $2) - $8::int + 1):],
				    context_snapshot = CASE WHEN $3 > COALESCE(risk_score, 0) THEN $4::jsonb ELSE context_snapshot END,
				    score_breakdown  = CASE WHEN $3 > COALESCE(risk_score, 0) THEN $5::jsonb ELSE score_breakdown END,
				    false_positive_risk = CASE WHEN $3 > COALESCE(risk_score, 0) THEN $9::numeric ELSE false_positive_risk END,
				    risk_score  = GREATEST(COALESCE(risk_score, 0), $3),
				    severity    = CASE
				                    WHEN COALESCE(array_position(ARRAY['informational','low','medium','high','critical'], lower($6)), 0)
				                       > COALESCE(array_position(ARRAY['informational','low','medium','high','critical'], lower(severity)), 0)
				                    THEN $6 ELSE severity END,
				    confidence  = GREATEST(COALESCE(confidence, 0), COALESCE($10::numeric, 0)),
				    related_rules = ARRAY(SELECT DISTINCT r FROM unnest(COALESCE(related_rules, '{}') || COALESCE($7, '{}'::text[])) AS r),
				    related_rule_ids = ARRAY(SELECT DISTINCT r FROM unnest(COALESCE(related_rule_ids, '{}') || COALESCE($11, '{}'::text[])) AS r),
				    last_seen_at = GREATEST(COALESCE(last_seen_at, timestamp), $12),
				    updated_at  = NOW()
				WHERE id = $1
				RETURNING id, timestamp, agent_id, rule_id, rule_title, severity, category,
					event_count, event_ids, mitre_tactics, mitre_techniques,
					matched_fields, matched_selections, context_data,
					status, assigned_to, resolution_notes,
					confidence, false_positive_risk,
					match_count, related_rules, related_rule_ids, combined_confidence,
					severity_promoted, original_severity,
					risk_score, context_snapshot, score_breakdown,
					created_at, updated_at, COALESCE(last_seen_at, timestamp)`
			row := tx.QueryRow(ctx, updateQuery, existingID, alert.EventIDs,
				alert.RiskScore, contextSnapshotJSON, scoreBreakdownJSON,
				alert.Severity, alert.RelatedRules, maxDedupEventIDs,
				alert.FalsePositiveRisk, alert.Confidence, alert.RelatedRuleIDs, seenAt)
			updated, scanErr := r.scanAlertFromRow(row)
			if scanErr != nil {
				return fmt.Errorf("scan updated alert: %w", scanErr)
			}
			resultAlert = updated
			isNew = false
			return nil
		}

		// Step 3: insert new alert
		insertQuery := `
			INSERT INTO sigma_alerts (
				timestamp, agent_id, rule_id, rule_title, severity, category,
				event_count, event_ids, mitre_tactics, mitre_techniques,
				matched_fields, matched_selections, context_data,
				status, confidence, false_positive_risk,
				match_count, related_rules, combined_confidence,
				severity_promoted, original_severity,
				risk_score, context_snapshot, score_breakdown, id, related_rule_ids, last_seen_at
			) VALUES (
				$1, $2, $3, $4, $5, $6,
				$7, $8, $9, $10,
				$11, $12, $13,
				$14, $15, $16,
				$17, $18, $19,
				$20, $21,
				$22, $23, $24, $25::uuid, $26, $27
			) RETURNING id, created_at, updated_at`

		row := tx.QueryRow(ctx, insertQuery,
			alert.Timestamp, alert.AgentID, alert.RuleID, alert.RuleTitle, alert.Severity, alert.Category,
			alert.EventCount, alert.EventIDs, alert.MitreTactics, alert.MitreTechniques,
			matchedFieldsJSON, alert.MatchedSelections, contextDataJSON,
			alert.Status, alert.Confidence, alert.FalsePositiveRisk,
			alert.MatchCount, alert.RelatedRules, alert.CombinedConfidence,
			alert.SeverityPromoted, alert.OriginalSeverity,
			alert.RiskScore, contextSnapshotJSON, scoreBreakdownJSON, alert.ID, alert.RelatedRuleIDs, seenAt,
		)
		alert.LastSeenAt = seenAt
		if scanErr := row.Scan(&alert.ID, &alert.CreatedAt, &alert.UpdatedAt); scanErr != nil {
			return fmt.Errorf("insert alert: %w", scanErr)
		}
		resultAlert = alert
		isNew = true
		return nil
	})

	if err != nil {
		return nil, false, err
	}
	return resultAlert, isNew, nil
}

// maxAlertMergeAge bounds how long one open alert absorbs a recurring
// detection (see UpsertWithDedup).
const maxAlertMergeAge = 24 * time.Hour

// Single-rule detections have no secondary rule IDs. pgx encodes a nil slice
// as SQL NULL, which bypasses the column default and violates NOT NULL. Keep
// the empty set explicit in both inserts and returned/callback records. The
// primary identity remains in rule_id; never fabricate a secondary match.
func normalizeRelatedRuleIDs(alert *Alert) {
	if alert.RelatedRuleIDs == nil {
		alert.RelatedRuleIDs = []string{}
	}
}

// MergeContextSnapshot shallow-merges patch into an alert's context_snapshot
// (jsonb ||), e.g. to record correlation results computed after insert.
func (r *PostgresAlertRepository) MergeContextSnapshot(ctx context.Context, id string, patch map[string]any) error {
	if _, err := uuid.Parse(id); err != nil {
		return fmt.Errorf("invalid alert id %q", id)
	}
	b, err := json.Marshal(patch)
	if err != nil {
		return err
	}
	_, err = r.pool.Exec(ctx,
		`UPDATE sigma_alerts SET context_snapshot = COALESCE(context_snapshot, '{}'::jsonb) || $2::jsonb, updated_at = NOW() WHERE id = $1::uuid`,
		id, string(b))
	return err
}

// scanAlertFromRow scans a pgx.Row into an Alert (used by UpsertWithDedup).
func (r *PostgresAlertRepository) scanAlertFromRow(row pgx.Row) (*Alert, error) {
	return r.scanAlert(row)
}

// GetByID retrieves an alert by its ID.
func (r *PostgresAlertRepository) GetByID(ctx context.Context, id string) (*Alert, error) {
	query := `
		SELECT id, timestamp, agent_id, rule_id, rule_title, severity, category,
			event_count, event_ids, mitre_tactics, mitre_techniques,
			matched_fields, matched_selections, context_data,
			status, assigned_to, resolution_notes,
			confidence, false_positive_risk,
			match_count, related_rules, related_rule_ids, combined_confidence,
			severity_promoted, original_severity,
			risk_score, context_snapshot, score_breakdown,
			created_at, updated_at, COALESCE(last_seen_at, timestamp)
		FROM sigma_alerts
		WHERE id = $1`

	return r.scanAlert(r.pool.QueryRow(ctx, query, id))
}

// List retrieves alerts matching the given filters.
func (r *PostgresAlertRepository) List(ctx context.Context, filters AlertFilters) ([]*Alert, int64, error) {
	// Build WHERE clause
	var conditions []string
	var args []interface{}
	argNum := 1

	if filters.AgentID != "" {
		conditions = append(conditions, fmt.Sprintf("agent_id = $%d", argNum))
		args = append(args, filters.AgentID)
		argNum++
	}
	if filters.RuleID != "" {
		conditions = append(conditions, fmt.Sprintf("rule_id = $%d", argNum))
		args = append(args, filters.RuleID)
		argNum++
	}
	if len(filters.Severity) > 0 {
		conditions = append(conditions, fmt.Sprintf("severity = ANY($%d)", argNum))
		args = append(args, filters.Severity)
		argNum++
	}
	if len(filters.Status) > 0 {
		conditions = append(conditions, fmt.Sprintf("status = ANY($%d)", argNum))
		args = append(args, filters.Status)
		argNum++
	}
	if !filters.DateFrom.IsZero() {
		conditions = append(conditions, fmt.Sprintf("timestamp >= $%d", argNum))
		args = append(args, filters.DateFrom)
		argNum++
	}
	if !filters.DateTo.IsZero() {
		conditions = append(conditions, fmt.Sprintf("timestamp <= $%d", argNum))
		args = append(args, filters.DateTo)
		argNum++
	}
	if filters.Search != "" {
		conditions = append(conditions, fmt.Sprintf("(rule_title ILIKE $%d OR agent_id ILIKE $%d OR rule_id ILIKE $%d)", argNum, argNum, argNum))
		args = append(args, "%"+filters.Search+"%")
		argNum++
	}

	whereClause := ""
	if len(conditions) > 0 {
		whereClause = "WHERE " + strings.Join(conditions, " AND ")
	}

	// Sort — allowlist guards against SQL injection from the SortBy field.
	// risk_score DESC is the primary SOC triage sort; timestamp DESC is the default.
	allowedSortColumns := map[string]string{
		"timestamp":  "timestamp",
		"risk_score": "risk_score",
		"severity":   "severity",
		"status":     "status",
		"rule_id":    "rule_id",
		"agent_id":   "agent_id",
	}
	sortBy := "timestamp"
	if col, ok := allowedSortColumns[filters.SortBy]; ok {
		sortBy = col
	}
	sortOrder := "DESC"
	if filters.SortOrder == "asc" {
		sortOrder = "ASC"
	}

	// Limit/Offset
	limit := 50
	if filters.Limit > 0 {
		limit = filters.Limit
	}
	offset := filters.Offset

	// Count query
	countQuery := fmt.Sprintf("SELECT COUNT(*) FROM sigma_alerts %s", whereClause)
	var total int64
	if err := r.pool.QueryRow(ctx, countQuery, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("failed to count alerts: %w", err)
	}

	// Data query
	dataQuery := fmt.Sprintf(`
		SELECT id, timestamp, agent_id, rule_id, rule_title, severity, category,
			event_count, event_ids, mitre_tactics, mitre_techniques,
			matched_fields, matched_selections, context_data,
			status, assigned_to, resolution_notes,
			confidence, false_positive_risk,
			match_count, related_rules, related_rule_ids, combined_confidence,
			severity_promoted, original_severity,
			risk_score, context_snapshot, score_breakdown,
			created_at, updated_at, COALESCE(last_seen_at, timestamp)
		FROM sigma_alerts %s
		ORDER BY %s %s
		LIMIT %d OFFSET %d`,
		whereClause, sortBy, sortOrder, limit, offset)

	rows, err := r.pool.Query(ctx, dataQuery, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to list alerts: %w", err)
	}
	defer rows.Close()

	var alerts []*Alert
	for rows.Next() {
		alert, err := r.scanAlertRow(rows)
		if err != nil {
			return nil, 0, err
		}
		alerts = append(alerts, alert)
	}

	return alerts, total, nil
}

// Update updates an existing alert.
func (r *PostgresAlertRepository) Update(ctx context.Context, id string, alert *Alert) (*Alert, error) {
	matchedFieldsJSON, _ := json.Marshal(alert.MatchedFields)
	contextDataJSON, _ := json.Marshal(alert.ContextData)

	query := `
		UPDATE sigma_alerts SET
			rule_title = $2, severity = $3, category = $4,
			event_count = $5, event_ids = $6,
			matched_fields = $7, context_data = $8,
			status = $9, assigned_to = $10, resolution_notes = $11,
			confidence = $12, false_positive_risk = $13
		WHERE id = $1
		RETURNING updated_at`

	err := r.pool.QueryRow(ctx, query,
		id, alert.RuleTitle, alert.Severity, alert.Category,
		alert.EventCount, alert.EventIDs,
		matchedFieldsJSON, contextDataJSON,
		alert.Status, alert.AssignedTo, alert.ResolutionNotes,
		alert.Confidence, alert.FalsePositiveRisk,
	).Scan(&alert.UpdatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to update alert: %w", err)
	}

	alert.ID = id
	return alert, nil
}

// UpdateStatus updates just the status of an alert.
func (r *PostgresAlertRepository) UpdateStatus(ctx context.Context, id string, status string, notes string) error {
	query := `UPDATE sigma_alerts SET status = $2, resolution_notes = $3 WHERE id = $1`
	_, err := r.pool.Exec(ctx, query, id, status, notes)
	return err
}

// Delete removes an alert from the database.
func (r *PostgresAlertRepository) Delete(ctx context.Context, id string) error {
	_, err := r.pool.Exec(ctx, "DELETE FROM sigma_alerts WHERE id = $1", id)
	return err
}

// GetStats retrieves aggregate alert statistics.
func (r *PostgresAlertRepository) GetStats(ctx context.Context) (*AlertStats, error) {
	stats := &AlertStats{
		BySeverity: make(map[string]int64),
		ByStatus:   make(map[string]int64),
		ByRule:     make(map[string]int64),
		ByAgent:    make(map[string]int64),
		ByTactic:   make(map[string]int64),
	}

	// Total
	r.pool.QueryRow(ctx, "SELECT COUNT(*) FROM sigma_alerts").Scan(&stats.TotalAlerts)

	// Last 24h
	r.pool.QueryRow(ctx, "SELECT COUNT(*) FROM sigma_alerts WHERE timestamp > NOW() - INTERVAL '24 hours'").Scan(&stats.Last24Hours)

	// Last 7d
	r.pool.QueryRow(ctx, "SELECT COUNT(*) FROM sigma_alerts WHERE timestamp > NOW() - INTERVAL '7 days'").Scan(&stats.Last7Days)

	// By severity
	rows, _ := r.pool.Query(ctx, "SELECT severity, COUNT(*) FROM sigma_alerts GROUP BY severity")
	for rows.Next() {
		var sev string
		var count int64
		rows.Scan(&sev, &count)
		stats.BySeverity[sev] = count
	}
	rows.Close()

	// By status
	rows, _ = r.pool.Query(ctx, "SELECT status, COUNT(*) FROM sigma_alerts GROUP BY status")
	for rows.Next() {
		var status string
		var count int64
		rows.Scan(&status, &count)
		stats.ByStatus[status] = count
	}
	rows.Close()

	// Avg detection confidence (0..1). This previously reported
	// AVG(risk_score)/100, conflating contextual risk with detection confidence.
	r.pool.QueryRow(ctx, "SELECT COALESCE(AVG(confidence), 0)::float8 FROM sigma_alerts").Scan(&stats.AvgConfidence)

	// By rule
	rowsRule, _ := r.pool.Query(ctx, "SELECT rule_title, COUNT(*) FROM sigma_alerts GROUP BY rule_title")
	for rowsRule.Next() {
		var title string
		var count int64
		rowsRule.Scan(&title, &count)
		stats.ByRule[title] = count
	}
	rowsRule.Close()

	// By agent (top 10 most-alerted endpoints)
	rowsAgent, _ := r.pool.Query(ctx, "SELECT agent_id, COUNT(*) FROM sigma_alerts GROUP BY agent_id ORDER BY COUNT(*) DESC LIMIT 10")
	for rowsAgent.Next() {
		var agentID string
		var count int64
		rowsAgent.Scan(&agentID, &count)
		stats.ByAgent[agentID] = count
	}
	rowsAgent.Close()

	// By tactic — unnest() expands the array column into individual rows
	rowsTactic, _ := r.pool.Query(ctx, `
		SELECT tactic, COUNT(*)
		FROM sigma_alerts, unnest(mitre_tactics) AS tactic
		WHERE mitre_tactics IS NOT NULL
		GROUP BY tactic
		ORDER BY COUNT(*) DESC
		LIMIT 14
	`)
	for rowsTactic.Next() {
		var tactic string
		var count int64
		rowsTactic.Scan(&tactic, &count)
		stats.ByTactic[tactic] = count
	}
	rowsTactic.Close()

	return stats, nil
}

// GetTimeline retrieves timeline data for the alert chart.
func (r *PostgresAlertRepository) GetTimeline(ctx context.Context, from, to, granularity string) ([]*TimelineDataPoint, error) {
	var trunc string
	switch granularity {
	case "1d":
		trunc = "day"
	default:
		trunc = "hour"
	}

	query := fmt.Sprintf(`
		SELECT 
			date_trunc('%s', timestamp) as bucket,
			COUNT(*) FILTER (WHERE severity = 'critical') as critical,
			COUNT(*) FILTER (WHERE severity = 'high') as high,
			COUNT(*) FILTER (WHERE severity = 'medium') as medium,
			COUNT(*) FILTER (WHERE severity = 'low') as low,
			COUNT(*) FILTER (WHERE severity = 'informational') as informational
		FROM sigma_alerts
		WHERE timestamp >= $1::timestamp AND timestamp <= $2::timestamp
		GROUP BY bucket
		ORDER BY bucket ASC
	`, trunc)

	rows, err := r.pool.Query(ctx, query, from, to)
	if err != nil {
		return nil, fmt.Errorf("failed to query timeline: %w", err)
	}
	defer rows.Close()

	var timeline []*TimelineDataPoint
	for rows.Next() {
		pt := &TimelineDataPoint{}
		if err := rows.Scan(&pt.Timestamp, &pt.Critical, &pt.High, &pt.Medium, &pt.Low, &pt.Informational); err != nil {
			return nil, err
		}
		timeline = append(timeline, pt)
	}

	if timeline == nil {
		timeline = make([]*TimelineDataPoint, 0)
	}

	return timeline, nil
}

// FindRecent finds recent similar alerts for deduplication.
func (r *PostgresAlertRepository) FindRecent(ctx context.Context, agentID, ruleID string, since time.Time) (*Alert, error) {
	query := `
		SELECT id, timestamp, agent_id, rule_id, rule_title, severity, category,
			event_count, event_ids, mitre_tactics, mitre_techniques,
			matched_fields, matched_selections, context_data,
			status, assigned_to, resolution_notes,
			confidence, false_positive_risk,
			match_count, related_rules, related_rule_ids, combined_confidence,
			severity_promoted, original_severity,
			risk_score, context_snapshot, score_breakdown,
			created_at, updated_at, COALESCE(last_seen_at, timestamp)
		FROM sigma_alerts
		WHERE agent_id = $1 AND rule_id = $2 AND timestamp >= $3
		ORDER BY timestamp DESC
		LIMIT 1`

	alert, err := r.scanAlert(r.pool.QueryRow(ctx, query, agentID, ruleID, since))
	if err == pgx.ErrNoRows {
		return nil, nil // Not found is ok for dedup
	}
	return alert, err
}

// IncrementEventCount increments the event count for an existing alert.
func (r *PostgresAlertRepository) IncrementEventCount(ctx context.Context, id string, eventIDs []string) error {
	query := `
		UPDATE sigma_alerts 
		SET event_count = event_count + $2,
		    event_ids = event_ids || $3
		WHERE id = $1`
	_, err := r.pool.Exec(ctx, query, id, len(eventIDs), eventIDs)
	return err
}

// BulkUpdateStatus updates the status of multiple alerts at once.
func (r *PostgresAlertRepository) BulkUpdateStatus(ctx context.Context, ids []string, status string) error {
	query := `UPDATE sigma_alerts SET status = $1, updated_at = NOW() WHERE id = ANY($2)`
	_, err := r.pool.Exec(ctx, query, status, ids)
	return err
}

// Close closes the repository.
func (r *PostgresAlertRepository) Close() error {
	return nil // Pool is managed externally
}

// scanAlert scans a single alert from a QueryRow.
func (r *PostgresAlertRepository) scanAlert(row pgx.Row) (*Alert, error) {
	var alert Alert
	var matchedFieldsJSON, contextDataJSON, contextSnapshotJSON, scoreBreakdownJSON []byte
	var assignedTo, resolutionNotes, originalSeverity *string

	err := row.Scan(
		&alert.ID, &alert.Timestamp, &alert.AgentID, &alert.RuleID, &alert.RuleTitle,
		&alert.Severity, &alert.Category, &alert.EventCount, &alert.EventIDs,
		&alert.MitreTactics, &alert.MitreTechniques,
		&matchedFieldsJSON, &alert.MatchedSelections, &contextDataJSON,
		&alert.Status, &assignedTo, &resolutionNotes,
		&alert.Confidence, &alert.FalsePositiveRisk,
		&alert.MatchCount, &alert.RelatedRules, &alert.RelatedRuleIDs, &alert.CombinedConfidence,
		&alert.SeverityPromoted, &originalSeverity,
		&alert.RiskScore, &contextSnapshotJSON, &scoreBreakdownJSON,
		&alert.CreatedAt, &alert.UpdatedAt, &alert.LastSeenAt,
	)

	if err != nil {
		return nil, err
	}

	json.Unmarshal(matchedFieldsJSON, &alert.MatchedFields)
	json.Unmarshal(contextDataJSON, &alert.ContextData)
	json.Unmarshal(contextSnapshotJSON, &alert.ContextSnapshot)
	json.Unmarshal(scoreBreakdownJSON, &alert.ScoreBreakdown)
	if assignedTo != nil {
		alert.AssignedTo = *assignedTo
	}
	if resolutionNotes != nil {
		alert.ResolutionNotes = *resolutionNotes
	}
	if originalSeverity != nil {
		alert.OriginalSeverity = *originalSeverity
	}

	return &alert, nil
}

// scanAlertRow scans a single alert from Rows.
func (r *PostgresAlertRepository) scanAlertRow(rows pgx.Rows) (*Alert, error) {
	var alert Alert
	var matchedFieldsJSON, contextDataJSON, contextSnapshotJSON, scoreBreakdownJSON []byte
	var assignedTo, resolutionNotes, originalSeverity *string

	err := rows.Scan(
		&alert.ID, &alert.Timestamp, &alert.AgentID, &alert.RuleID, &alert.RuleTitle,
		&alert.Severity, &alert.Category, &alert.EventCount, &alert.EventIDs,
		&alert.MitreTactics, &alert.MitreTechniques,
		&matchedFieldsJSON, &alert.MatchedSelections, &contextDataJSON,
		&alert.Status, &assignedTo, &resolutionNotes,
		&alert.Confidence, &alert.FalsePositiveRisk,
		&alert.MatchCount, &alert.RelatedRules, &alert.RelatedRuleIDs, &alert.CombinedConfidence,
		&alert.SeverityPromoted, &originalSeverity,
		&alert.RiskScore, &contextSnapshotJSON, &scoreBreakdownJSON,
		&alert.CreatedAt, &alert.UpdatedAt, &alert.LastSeenAt,
	)

	if err != nil {
		return nil, err
	}

	json.Unmarshal(matchedFieldsJSON, &alert.MatchedFields)
	json.Unmarshal(contextDataJSON, &alert.ContextData)
	json.Unmarshal(contextSnapshotJSON, &alert.ContextSnapshot)
	json.Unmarshal(scoreBreakdownJSON, &alert.ScoreBreakdown)
	if assignedTo != nil {
		alert.AssignedTo = *assignedTo
	}
	if resolutionNotes != nil {
		alert.ResolutionNotes = *resolutionNotes
	}
	if originalSeverity != nil {
		alert.OriginalSeverity = *originalSeverity
	}

	return &alert, nil
}

// Ensure interface compliance
var _ AlertRepository = (*PostgresAlertRepository)(nil)

func init() {
	_ = logger.Info // Reference logger to avoid unused import
}
