-- Migration: 056_bind_build_id_to_enrollment_tokens
--
-- Supersedes split-key architecture (migration 055):
--   * Removes key_b and key_b_served (never shipped to production).
--   * Adds build_id UUID: a random identifier generated by the agent-builder
--     at build time and stored in the binary via ldflag.
--
-- Security model (BuildID + HMAC):
--   * Binary embeds: BuildID (UUID) + HMAC-SHA256(key=token, msg=buildID)
--   * Binary contains ZERO token material — no ciphertext, no key half.
--   * Agent receives token via stdin at install time only.
--   * Local HMAC check before any network call rejects wrong tokens.
--   * Server looks up enrollment record by BuildID and verifies token_hash.

-- Remove split-key columns (never shipped to production).
ALTER TABLE public.enrollment_tokens
    DROP COLUMN IF EXISTS key_b,
    DROP COLUMN IF EXISTS key_b_served;

-- Add build_id: one UUID per binary build.
ALTER TABLE public.enrollment_tokens
    ADD COLUMN IF NOT EXISTS build_id UUID DEFAULT NULL;

COMMENT ON COLUMN public.enrollment_tokens.build_id IS
    'Random UUID generated at agent build time. Injected into the binary via ldflag '
    '(-X main.EmbeddedBuildID). The binary also carries HMAC-SHA256(key=token, msg=build_id) '
    'so the agent can verify the token locally before any network call. '
    'NULL = token has not been used to build a binary yet. '
    'Set atomically by StoreBuildID (WHERE build_id IS NULL) — prevents double-build races.';

-- Partial unique index: each build_id may only belong to one token record.
-- NULLs are excluded from unique indexes in PostgreSQL, so unbuildable tokens are fine.
CREATE UNIQUE INDEX IF NOT EXISTS uq_enrollment_tokens_build_id
    ON public.enrollment_tokens(build_id)
    WHERE build_id IS NOT NULL;
